import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

import { Menu } from 'antd';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { HomeOutlined } from '@ant-design/icons';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ maxWidth: '1280px', margin: '0 auto' }}
      >
        <AntdRegistry>
          <Menu
            items={[
              {
                label: <Link href="/">Home</Link>,
                key: 'home',
                icon: <HomeOutlined />,
              },
            ]}
            mode="horizontal"
            style={{
              marginBottom: '10px',
            }}
          />
          {children}
        </AntdRegistry>
      </body>
    </html>
  );
}
