import type { Metadata } from 'next';
import Link from 'next/link';

import { ConfigProvider, Menu, theme } from 'antd';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Title from 'antd/es/typography/Title';

import DarkTheme from '@/theme';

export const metadata: Metadata = {
  title: 'Hacker news',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{
          maxWidth: '1280px',
          margin: '0 auto',
          backgroundColor: '#141414',
        }}
      >
        <AntdRegistry>
          <DarkTheme>
            <Menu
              items={[
                {
                  label: (
                    <Link href="/">
                      <Title level={3}>Hacker News</Title>
                    </Link>
                  ),
                  key: 'home',
                },
              ]}
              mode="horizontal"
              style={{
                marginBottom: '10px',
                padding: '0 10px',
                width: '100%',
                border: '1px solid rgba(253, 253, 253, 0.12)',
                borderRadius: '10px',
              }}
            />
            {children}
          </DarkTheme>
        </AntdRegistry>
      </body>
    </html>
  );
}
