import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

import { Menu, MenuProps } from 'antd';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { HomeOutlined } from '@ant-design/icons';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const items: MenuProps['items'] = [
  {
    label: <Link href="/">Home</Link>,
    key: 'home',
    icon: <HomeOutlined />,
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <Menu
            // style={{ width: '100%', marginBottom: '20px' }}
            items={items}
            mode="horizontal"
          />
          {children}
        </AntdRegistry>
      </body>
    </html>
  );
}
